{ pkgs, ... }:
{
  imports = [
    /path/to/nix-csf
  ];

  services.openssh = {
    enable = true;
    ports = [ 112 ];
  };

  services.netdata = {
    enable = true;
    package = pkgs.netdataCloud;
    config.web = {
      "bind to" = "tcp:0.0.0.0:19999";
      # Restrict dashboard/badges to operator CIDRs only.
      "allow dashboard from" = "localhost 127.0.0.1 ::1 172.16.0.0/16";
      "allow badges from" = "localhost 127.0.0.1 ::1 172.16.0.0/16";
    };
  };

  services.nixCsf = {
    enable = true;
    threatProfile = "custom";

    # Global public services.
    openTCPPorts = [ 80 443 112 ];

    # Restrict SSH to Bulgaria only.
    country.portAllow = {
      enable = true;
      countries = [ "BG" ];
      tcpPorts = [ 112 ];
    };

    # Generated by nix-csf-import-csf.
    localFiles = {
      enable = true;
      failOnMissing = true;
      allow = [ "/var/lib/nix-csf/imported/legacy-csf-allow.local" ];
      deny = [ "/var/lib/nix-csf/imported/legacy-csf-deny.local" ];
      ignore = [ "/var/lib/nix-csf/imported/legacy-csf-ignore.local" ];
    };

    observability.metrics = {
      enable = true;
      outputFile = "/var/lib/nix-csf/metrics.prom";
    };

    netdata = {
      enable = true;
      updateEvery = 15;
      installHealthAlarms = true;
      alertRecipient = "sysadmin";
    };

    autoRefresh.onCalendar = "hourly";
  };
}
