{
  description = "nix-csf test server: global web ports, BG-only SSH, Netdata, CSF import, LFD escalation";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # Pin this to your release tag in production, for example:
    # nix-csf.url = "github:<org>/nix-csf?ref=v1.0.0";
    nix-csf.url = "github:cheirekov/nix-csf";
  };

  outputs = { nixpkgs, nix-csf, ... }: {
    nixosConfigurations.test-server = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        nix-csf.nixosModules.default
        ({ pkgs, ... }: {
          services.openssh = {
            enable = true;
            ports = [ 112 ];
          };

          services.netdata = {
            enable = true;
            package = pkgs.netdataCloud;
            config.web = {
              "bind to" = "tcp:0.0.0.0:19999";
              # Restrict dashboard/badges to operator CIDRs only.
              "allow dashboard from" = "localhost 127.0.0.1 ::1 172.16.0.0/16";
              "allow badges from" = "localhost 127.0.0.1 ::1 172.16.0.0/16";
            };
          };

          services.nixCsf = {
            enable = true;
            threatProfile = "custom";

            # Public services.
            openTCPPorts = [ 80 443 112 ];

            # Restrict SSH to Bulgaria only.
            country.portAllow = {
              enable = true;
              countries = [ "BG" ];
              tcpPorts = [ 112 ];
            };

            # Imported legacy CSF overlays (generated by nix-csf-import-csf).
            localFiles = {
              enable = true;
              failOnMissing = true;
              allow = [ "/var/lib/nix-csf/imported/legacy-csf-allow.local" ];
              deny = [ "/var/lib/nix-csf/imported/legacy-csf-deny.local" ];
              ignore = [ "/var/lib/nix-csf/imported/legacy-csf-ignore.local" ];
            };

            # Local mutable control-plane for LFD + escalation path.
            controlPlane = {
              enable = true;
              requireAuth = false; # test/staging only
              environment = "lab";
              escalation = {
                enable = true;
                tempBanThreshold = 3;
                windowSeconds = 900;
              };
            };

            # Pull permanent deny/allow/ignore policy from local control-plane snapshot.
            clusterPolicy = {
              enable = true;
              url = "http://127.0.0.1:18081/snapshots/lab/cluster-policy.json";
              requireHTTPS = false; # local-only
              failOpen = true;
            };

            # Pull temporary bans from local control-plane snapshot.
            dynamicOffenders = {
              enable = true;
              url = "http://127.0.0.1:18081/snapshots/lab/dynamic-offenders.json";
              requireHTTPS = false; # local-only
              failOpen = true;
              defaultEntryTTLSeconds = 900;
            };

            # Nix-native LFD behavior: journal -> temp ban -> optional escalation to permanent deny.
            lfdDetector = {
              enable = true;
              journalIdentifier = "sshd";
              threshold = 5;
              windowSeconds = 300;
              banTTLSeconds = 900;
              refreshAfterBan = true;
            };

            observability.metrics = {
              enable = true;
              outputFile = "/var/lib/nix-csf/metrics.prom";
            };

            netdata = {
              enable = true;
              updateEvery = 15;
              installHealthAlarms = true;
              alertRecipient = "sysadmin";
            };

            autoRefresh.onCalendar = "hourly";
          };
        })
      ];
    };
  };
}
